export const array = [
    {
        id:1,
        name:"abhiram",
        age:"23",
        email:"xyz@gmail.com"
        
    },
    {
        id:1,
        name:"saidulu",
        age:"23",
        email:"xyz@gmail.com"
    },
    {
        id:1,
        name:"saikiran",
        age:"23",
        email:"xyz@gmail.com"
    },
    {
        id:1,
        name:"sumanth",
        age:"23",
        email:"xyz@gmail.com"
    },
    {
        id:1,
        name:"srikanth",
        age:"23",
        email:"xyz@gmail.com"
    }
]